name=input("Enter your name: ")
age=input("Enter your age: ")
college=input("Enter your College: ")
department=input("Enter your Department: ")
print("-----Student Details-----")
print("Name      :",name)
print("Age       : ",age)
print("College   : ",college)
print("Department: ",department)